[workspace]
members = [
    "lib",
    "cli",
    "gui",
]
resolver = "3"

[workspace.dependencies]
argh = "0.1.13"
macroquad = { version = "0.4.13", features = ["audio"] }
quad-snd = "0.2.8"
rand = "0.9.1"
